### ISSUE TITLE
If object is Vec3 instance

### ISSUE THREAD

**Issue by wmantly** [PrismarineJS/node-vec3#27]
Hello, I am trying to write code and figure out if an argument passed is a Vec3 instance. `typeof` and `instanceof` do not work.

```js
> c
Vec3 { x: 371.799932938009, y: 54, z: 15.142123535900657 }
> typeof c
'object'
> c instanceof Vec3
false
```

**Comment by wmantly** [comment]
After reading the source, I see why it doesn't work. You have the constructor function outside the class https://github.com/PrismarineJS/node-vec3/blob/master/index.js#L215

Please do not do this with ES6 classes, as you break `instanceof` and the wider assumptions about how classes are implemented. The function you have on line 215 should be the class constructor.

**Comment by rom1504** [comment]
It's not a constructor

**Comment by IceTank** [comment]
```js
const { Vec3 } = require('vec3')
const c = new Vec3(0, 0, 0)
c instanceof Vec3 // > true
```
This works. 

You have to import the class not the default vec3 builder function. The function does things the class constructor cannot do for instance string input instead off numbers.
