### ISSUE TITLE
add github action for CI and CD

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-vec3#5]

**Comment by rom1504** [comment]
did CI
for CD I need more rights here or we need to transfer to prismarinejs (to add npm token)

**Comment by andrewrk** [comment]
You can have more rights, the repo is yours if you want it. Just tell me what you want me to do

**Comment by rom1504** [comment]
Ok thanks. I think transferring the repo to PrismarineJS organization is the best thing to do, it will ensure it stays maintained (we are several people maintaining things there, including me and @Karang )

Could you do that ? (In settings of the repo you should have the option to transfer it to PrismarineJS)

**Comment by rom1504** [comment]
Hi @andrewrk , could you transfer this repo to http://github.com/PrismarineJS/ organization please ?

**Comment by andrewrk** [comment]
Done

**Comment by rom1504** [comment]
thanks !
